import Head from "next/head";
import AboutMain from "../components/About/AboutMain";
import Footer from "../components/Layout/Footer/Footer";
import Header from "../components/Layout/Header";

export default function About() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
       
      </Head>

      <Header />
      <AboutMain />
      <Footer />
    </>
  );
}
