import Head from "next/head";
import ContactMain from "../components/Contact/ContactMain";
import Footer from "../components/Layout/Footer/Footer";
import Header from "../components/Layout/Header";

export default function Contact() {
  return (
    <>
      <Head>
        <title>Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <Header />
      <ContactMain />
      <Footer />
    </>
  );
}
