import Head from "next/head";
import HomeMain from "../components/Home/HomeMain";
import Footer from "../components/Layout/Footer/Footer";
import Header from "../components/Layout/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Apple</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>

      <Header />
      <HomeMain />
      <Footer />
    </>
  );
}
