import Head from "next/head";
import CourseMain from "../components/Course/CourseMain";
import Footer from "../components/Layout/Footer/Footer";
import Header from "../components/Layout/Header";

export default function Course() {
  return (
    <>
      <Head>
        <title>Product</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>

      <Header />
      <CourseMain />
      <Footer />
    </>
  );
}
